python3 web_ncbi.py -i Pisum_sativum -l Pisum_sativum.log -o Pisum_sativum.combine_file
python3 web_ncbi.py -i Quercus_robur -l Quercus_robur.log -o Quercus_robur.combine_file
python3 web_ncbi.py -i Vigna_unguiculata -l Vigna_unguiculata.log -o Vigna_unguiculata.combine_file
python3 web_ncbi.py -i Fagus_sylvatica -l Fagus_sylvatica.log -o Fagus_sylvatica.combine_file
python3 web_ncbi.py -i Arachis_duranensis -l Arachis_duranensis.log -o Arachis_duranensis.combine_file
python3 web_ncbi.py -i Arachis_ipaensis -l Arachis_ipaensis.log -o Arachis_ipaensis.combine_file
python3 web_ncbi.py -i Arachis_monticola -l Arachis_monticola.log -o Arachis_monticola.combine_file
python3 web_ncbi.py -i Cajanus_cajan -l Cajanus_cajan.log -o Cajanus_cajan.combine_file
python3 web_ncbi.py -i Cicer_reticulatum -l Cicer_reticulatum.log -o Cicer_reticulatum.combine_file
python3 web_ncbi.py -i Vigna_radiata -l Vigna_radiata.log -o Vigna_radiata.combine_file
python3 web_ncbi.py -i Punica_granatum -l Punica_granatum.log -o Punica_granatum.combine_file
python3 web_ncbi.py -i Gossypium_arboreum -l Gossypium_arboreum.log -o Gossypium_arboreum.combine_file
python3 web_ncbi.py -i Gossypium_barbadense -l Gossypium_barbadense.log -o Gossypium_barbadense.combine_file
python3 web_ncbi.py -i Gossypium_hirsutum -l Gossypium_hirsutum.log -o Gossypium_hirsutum.combine_file
python3 web_ncbi.py -i Hibiscus_syriacus -l Hibiscus_syriacus.log -o Hibiscus_syriacus.combine_file
python3 web_ncbi.py -i Nelumbo_nucifera -l Nelumbo_nucifera.log -o Nelumbo_nucifera.combine_file
python3 web_ncbi.py -i Fraxinus_excelsior -l Fraxinus_excelsior.log -o Fraxinus_excelsior.combine_file
python3 web_ncbi.py -i Olea_europaea -l Olea_europaea.log -o Olea_europaea.combine_file
python3 web_ncbi.py -i Erythranthe_guttata -l Erythranthe_guttata.log -o Erythranthe_guttata.combine_file
python3 web_ncbi.py -i Fragaria_vesca -l Fragaria_vesca.log -o Fragaria_vesca.combine_file
python3 web_ncbi.py -i Fragaria_ananassa -l Fragaria_ananassa.log -o Fragaria_ananassa.combine_file
python3 web_ncbi.py -i Prunus_persica -l Prunus_persica.log -o Prunus_persica.combine_file
python3 web_ncbi.py -i Malus_domestica -l Malus_domestica.log -o Malus_domestica.combine_file
python3 web_ncbi.py -i Prunus_dulcis -l Prunus_dulcis.log -o Prunus_dulcis.combine_file
python3 web_ncbi.py -i Prunus_avium -l Prunus_avium.log -o Prunus_avium.combine_file
python3 web_ncbi.py -i Citrus_clementina -l Citrus_clementina.log -o Citrus_clementina.combine_file
python3 web_ncbi.py -i Citrus_maxima -l Citrus_maxima.log -o Citrus_maxima.combine_file
python3 web_ncbi.py -i Citrus_sinensis -l Citrus_sinensis.log -o Citrus_sinensis.combine_file
python3 web_ncbi.py -i Citrus_reticulata -l Citrus_reticulata.log -o Citrus_reticulata.combine_file
python3 web_ncbi.py -i Populus_euphratica -l Populus_euphratica.log -o Populus_euphratica.combine_file
python3 web_ncbi.py -i Populus_trichocarpa -l Populus_trichocarpa.log -o Populus_trichocarpa.combine_file
python3 web_ncbi.py -i Capsicum_annuum -l Capsicum_annuum.log -o Capsicum_annuum.combine_file
python3 web_ncbi.py -i Nicotiana_benthamiana -l Nicotiana_benthamiana.log -o Nicotiana_benthamiana.combine_file
python3 web_ncbi.py -i Nicotiana_tabacum -l Nicotiana_tabacum.log -o Nicotiana_tabacum.combine_file
python3 web_ncbi.py -i Solanum_habrochaites -l Solanum_habrochaites.log -o Solanum_habrochaites.combine_file
python3 web_ncbi.py -i Solanum_lycopersicum -l Solanum_lycopersicum.log -o Solanum_lycopersicum.combine_file
python3 web_ncbi.py -i Solanum_melongena -l Solanum_melongena.log -o Solanum_melongena.combine_file
python3 web_ncbi.py -i Solanum_pennellii -l Solanum_pennellii.log -o Solanum_pennellii.combine_file
python3 web_ncbi.py -i Solanum_pimpinellifolium -l Solanum_pimpinellifolium.log -o Solanum_pimpinellifolium.combine_file
python3 web_ncbi.py -i Solanum_tuberosum -l Solanum_tuberosum.log -o Solanum_tuberosum.combine_file
python3 web_ncbi.py -i Nicotiana_attenuata -l Nicotiana_attenuata.log -o Nicotiana_attenuata.combine_file
python3 web_ncbi.py -i Vitis_vinifera -l Vitis_vinifera.log -o Vitis_vinifera.combine_file
python3 web_ncbi.py -i Chenopodium_quinoa -l Chenopodium_quinoa.log -o Chenopodium_quinoa.combine_file
python3 web_ncbi.py -i Catharanthus_roseus -l Catharanthus_roseus.log -o Catharanthus_roseus.combine_file
python3 web_ncbi.py -i Panax_notoginseng -l Panax_notoginseng.log -o Panax_notoginseng.combine_file
python3 web_ncbi.py -i Humulus_lupulus -l Humulus_lupulus.log -o Humulus_lupulus.combine_file
python3 web_ncbi.py -i Tarenaya_hassleriana -l Tarenaya_hassleriana.log -o Tarenaya_hassleriana.combine_file
python3 web_ncbi.py -i Juglans_regia -l Juglans_regia.log -o Juglans_regia.combine_file
python3 web_ncbi.py -i Salvia_miltiorrhiza -l Salvia_miltiorrhiza.log -o Salvia_miltiorrhiza.combine_file
python3 web_ncbi.py -i Moringa_oleifera -l Moringa_oleifera.log -o Moringa_oleifera.combine_file
python3 web_ncbi.py -i Eucalyptus_grandis -l Eucalyptus_grandis.log -o Eucalyptus_grandis.combine_file
python3 web_ncbi.py -i Coffea_arabica -l Coffea_arabica.log -o Coffea_arabica.combine_file
python3 web_ncbi.py -i Camellia_sinensis -l Camellia_sinensis.log -o Camellia_sinensis.combine_file
